### ISSUE TITLE
Troubles using Flux approach since Telerik 3.0.0 (new OnRead system etc.)

### ISSUE THREAD

**Issue by dylanbarquilla** [telerik/blazor-ui#165]
## Context 
In our application we use the Flux approach, with [Fluxor library](https://github.com/mrpmorris/Fluxor).
We have created [a post on the Telerik Blazor forum](https://www.telerik.com/forums/how-can-we-use-a-flux-approach-with-new-grid-system-new-onread-server-side-pagination-etc) to expose a concrete example and use case where we have some troubles since the Telerik 3.0.0 release. 

### Old practice
With the Flux approach, we bind our components to objects stored in a State. For example, we used to do the following:
`<TelerikGrid Data="@State.Houses"
             TotalCount="@State.TotalCount">`

### New practice
But now, we have to use OnRead events on components if we need to do some server side data manipulation (pagination or filtering a ComboBox data source for example). Use the OnRead event disable the mapping to Data parameter, but allow us to do the following:
```
protected async Task ReadItems(GridReadEventArgs args) {
  DataEnvelope DataResult = await FetchPagedData(args.Request.Page, args.Request.PageSize);
  args.Data = DataResult.CurrentPageData;
  args.Total = DataResult.TotalItemCount;
}
```

This is working very well if you want to use a classic pattern of:
**User interaction -> frontend ask for data -> wait the answer -> assign args.Data and args.Total with these values.**

But the pattern that we use (with Flux approach) is more like the following:
**User interaction -> frontend ask for data -> answer is saved in a State, with the creation of a new instance -> the direct binding between component parameters (Data and TotalCount in general) and the State does the work**

## The problem with that
With these new implementation and new approach, we are no longer able to use and respect the Flux pattern. We have created a "hack" in order to do it, but it forces us to subscribe to the event (action) fired when the request is completed (so the state has a new value), and to call the Rebind() method of the component in the callback of this event.

```
protected override void OnInitialized() {
  SubscribeToAction<SetHousesAction>(action => {
    if (GridRef is null) return;
    GridRef.Rebind();
  });

  base.OnInitialized();
}
```
### And now?
We have some questions with all of these elements:
- Is the new implementation compatible with Flux approach since Telerik 3.0.0?
- Is there any way to fully respect the Flux approach with new Telerik 3.0.0 OnRead system, or do we have to do the "subscribe to action" trick?
- Did we miss some information or something else? 

## Environment

* **Telerik UI for Blazor version:** 3.0.0 (and older)
* **Browser:** all
* **App Type** client

**Comment by marin-bratanov** [comment]
Hi, this repository contains sample projects that showcase specific scenarios. So, issues in it should relate to problems in those samples, or ideas for new ones. The forums are a great place to discuss coding practices or particular issues, and you can also open private support tickets to reach the development team directly. Thus, I have to close this one - let's keep further discussion in the appropriate place.
