### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by BenHayat** [telerik/blazor-ui#22]
For the next round of the live demo, I suggest to change the .cshtml extension of pages to .razor to stay current with MSFT naming. This way, visitors don't get confused with the older version of Blazor.

**Comment by ivanchev** [comment]
Hi Ben,

The live demos are already switched to razor, to comply with the latest version of Blazor.

We've however decided to keep the official demos application internal at this point, and focus this repository as an issue tracker. We do plan to add code samples and snippets here in the future, different than the demos application. Part of this decision is the particularities of the demos app, that are not specific to the components.

**Comment by BenHayat** [comment]
Hi;
Just to make I was clear about what I said, I meant these places in the demos.
![index](https://user-images.githubusercontent.com/7861196/57082823-81969f80-6cc5-11e9-88b0-d00dd496744f.jpg)

**Comment by ivanchev** [comment]
Oh, this is a template oversight - the pages are actually razor, but the template states them as cshtml. 

Thank you, I'll reopen this until we release the fix.

**Comment by BenHayat** [comment]
Yes, I knew the actual code uses .razor, as I have the solution. When I had sent the demo URL to friends, I noticed the .cshtml in the demos. No big deal, I just offered an extra pair of eyes. :-)

**Comment by ivanchev** [comment]
This is now fixed, and will be uploaded live next week
