### ISSUE TITLE
BlazingCoffee website does not start

### ISSUE THREAD

**Issue by FolkertVreeken** [telerik/blazor-ui#228]
BlazingCoffee website hangs on the loading indicator.
Even after updating Trial to paid commercial license.

**Comment by dimodi** [comment]
Hello, @FolkertVreeken ,

We are aware of two possible reasons for such a problem -

* Visual Studio hot reload is enabled. This feature does not work with non-default app roots, so [please disable it temporarily](https://github.com/telerik/blazor-ui/tree/master/sample-applications/blazing-coffee#running-the-sample-blazor-project).
* Your computer's regional settings have a non-US date format. This breaks the parsing of the [CSV file](https://github.com/telerik/blazor-ui/blob/master/sample-applications/blazing-coffee/BlazingCoffee/Server/wwwroot/imports/finserv.csv) during the [data source generation](https://github.com/telerik/blazor-ui/blob/master/sample-applications/blazing-coffee/BlazingCoffee/Server/Data/DbInitializer.cs#L1916). This is something that we can (and should) address in the future.

Does this throw enough light on the matter?

**Comment by FolkertVreeken** [comment]
Thanks. Disabling the hot reload feature did the trick.
Although, I did not get a 404 error before.
Anyway, it works.
