### ISSUE TITLE
Chart events

### ISSUE THREAD

**Issue by MarkTMcp** [telerik/blazor-ui#23]
Would be nice to have ChartEvents like GridEvents

Two use cases:
1) Click event for Series Legend that would be used to Hide/Show series.
2) Click event on series data point for drill-down to underlying data.

Currently using a hack with forms:
<img width="1040" alt="Annotation 2019-05-08 154720" src="https://user-images.githubusercontent.com/43792445/57403882-aa78d200-71a8-11e9-8c3c-ff491631a109.png">

**Comment by Stamo-Gochev** [comment]
Thanks for the suggestion. Indeed, this is an idea that can be added in a future version. You can also forward this suggestion to the feedback portal, where we can track the priority of the feature request using the number of votes that other people give:
https://feedback.telerik.com/blazor

**Comment by marin-bratanov** [comment]
You can follow the most common request for a click event here: [https://feedback.telerik.com/blazor/1412010-i-need-a-click-event-on-a-chart-element-such-as-a-specific-bar-in-a-bar-chart-or-a-slice-in-a-pie-chart](https://feedback.telerik.com/blazor/1412010-i-need-a-click-event-on-a-chart-element-such-as-a-specific-bar-in-a-bar-chart-or-a-slice-in-a-pie-chart).

This repo will contain examples and is not going to be used as an issue tracker for the component suite itself.
