### ISSUE TITLE
This solution may result in double poastback along your whole n-tier till the database

### ISSUE THREAD

**Issue by DanielTal** [telerik/blazor-ui#233]
because the call to StateHasChanged in the MainLayout , all your site using the mainlayout will double postback your requests

**Comment by dimodi** [comment]
Hello @DanielTal,

We use `StateHasChanged` in several `MainLayout` files for a specific purpose. Which one are you referring to?

* https://github.com/telerik/blazor-ui/blob/master/loader/slow-page-or-component/loader-container-main-layout-usage/Shared/MainLayout.razor#L31
* https://github.com/telerik/blazor-ui/blob/master/sample-applications/blazor-stocks/Client/Shared/MainLayout.razor#L91
* https://github.com/telerik/blazor-ui/blob/master/sample-applications/blazor-dashboard/BlazorDashboard/Shared/MainLayout.razor#L89
* https://github.com/telerik/blazor-ui/blob/master/drawer/select-on-load/select-on-load/Shared/MainLayout.razor#L67

I tested the [Dashboard app](https://github.com/telerik/blazor-ui/blob/master/sample-applications/blazor-dashboard/) and there is no double data request upon navigation.

**Comment by dimodi** [comment]
Hi @DanielTal ,

I am closing this issue for now. If you wish to continue the discussion, feel free to do so.
