### ISSUE TITLE
TelerikTestContext replacing IJSRuntime not ideal

### ISSUE THREAD

**Issue by egil** [telerik/blazor-ui#258]
I noticed that `TelerikTestContext` and `TelerikTestContextWithActualRoot` are replacing bUnits built-in `IJSRuntime` with a mock. While it does work, there are a bunch of edge cases and 1st party components that bUnit's version is configured to handle out of the box (e.g. the Virtualize component), so a better approach would be to set up everything that is needed to render Telerik components directly.

There are a bunch of ways to achieve this, so I am curious what `// mock the JS Interop service, you cannot use the one coming from the context ` refers to and will gladly help resolve any issues that are (if possible). If possible, outline the JSInterop requirements and I can help set things up.

https://github.com/telerik/blazor-ui/blob/8892d4f84331246bc2086be9806265a5b50eb6eb/testing/bUnit-justmock/Telerik.Blazor.BUnit.JustMock/Common/TelerikTestContext.cs#L21-L35

Related: https://github.com/bUnit-dev/bUnit/discussions/1175

**Comment by KristianMariyanov** [comment]
Hi, @egil 
Thanks for reaching out with a suggestion for improvement.

TBH, I don't think we knew that the `JSRuntimeMode.Loose` settings exist. I make the changes and the tests ran successfully. 

I'm pushing these changes to our sample project: https://github.com/telerik/blazor-ui/pull/259

Thank you.

**Comment by egil** [comment]
Ideally, you do not set the JSInterop globally to Loose, since that affects not only your javascript but also any other javascript there could be in use.

If your javascript is accessed via modules, you can instead make that configuration change just on the module level.

More details here: https://bunit.dev/docs/test-doubles/emulating-ijsruntime.html#support-for-importing-javascript-modules
