### ISSUE TITLE
Blazor Sidebar

### ISSUE THREAD

**Issue by LibongweM** [telerik/blazor-ui#261]
### Bug report

**For Support request - Please do not submit support request here, instead see the** [Telerik UI for Blazor forums](https://www.telerik.com/forums/blazor) or our [support system](http://www.telerik.com/support) **at Telerik.com** !

**For Feature Requests - please submit those into [our feedback portal](https://www.telerik.com/support/feedback)**

### Reproduction of the problem
_(bug report only)_
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem by referencing a sample project.

### Current behavior
_(optional)_
Provide additional information if the steps for reproducing the faulty behavior are not sufficient to describe the issue.

### Expected/desired behavior
Explain what the expected behavior of the functionality is

### Environment

* **Telerik UI for Blazor version:** x.y.z
* **Browser:** [all | Chrome XX | Firefox XX | Edge XX]
* **App Type** [server | client]

**Comment by dimodi** [comment]
@LibongweM - this issue seems empty, what did you intended to share with us?
