### ISSUE TITLE
 Focus is moving to the entire section under "sofia item" which is non interactive while navigating with tab key.

### ISSUE THREAD

**Issue by msftedad** [telerik/blazor-ui#270]
### Reproduction of the problem
1. Open URL [Blazor TabStrip Demos - Overview | Telerik UI for Blazor](https://demos.telerik.com/blazor-ui/tabstrip/overview).
2. After invoking to the URL Navigate to the page by tab key
3. Navigate to the sofia tab list by tab key
4. Observe the issue, after pressing the next tab key, the focus is moving to the entire section of non-interactive elements.

### Current behavior
Focus is moving to the entire section which is non interactive while navigating with tab key, after sofia item.

### Expected/desired behavior
When invoking with Tab key focus should move to the next interactive element i.e [Telerik UI for Blazor](https://www.telerik.com/blazor-ui) link, not on to the entire section of sofia tab.

### Environment

* **Telerik UI for Blazor version:** 4.2.0
* **Browser:** Edge Version: 118.0.2088.76 (Official build) (64-bit)

**Attachments:**
[Edad bug video.webm](https://github.com/telerik/blazor-ui/assets/93735775/719df256-b9e2-49b5-895d-fb2cc0bd0e17)

**Comment by msftedad** [comment]
Hi @dimodi, instead of the focus moving to the entire section, it would be better if the focus falls on the first interactive element of the Section.

**Comment by dimodi** [comment]
That's indeed an option with the [manual tab activation algorithm](https://www.w3.org/WAI/ARIA/apg/patterns/tabs/examples/tabs-manual/), but we are using [automatic activation](https://www.w3.org/WAI/ARIA/apg/patterns/tabs/examples/tabs-automatic/). In this case, it takes just one more tab to focus the first interactive element inside the active TabStrip container. We believe this behavior is more universal.
