### ISSUE TITLE
How would we add Recurrence support to this?

### ISSUE THREAD

**Issue by caviles** [telerik/blazor-ui#283]
### Bug report

For: https://github.com/telerik/blazor-ui/tree/master/scheduler/custom-edit-form

This is a great example but it does not show a primary feature Recurrence. Can you extend the sample to show this?

I see we would add this in the model but in these customs forms how would we support this in a format the scheduler would understand?

  public string? RecurrenceRule { get; set; }
  public List<DateTime>? RecurrenceExceptions { get; set; }
  public Guid? RecurrenceId { get; set; }

**Comment by dimodi** [comment]
@caviles 

This is not a support channel. Please use tickets for such questions.

Recurrence editing is currently not supported in custom Scheduler edit forms. You can vote and follow this feature request - https://feedback.telerik.com/blazor/1485984-expose-recurrenceeditor-component
