### ISSUE TITLE
Chart dissapearing

### ISSUE THREAD

**Issue by FenixCrafter** [telerik/blazor-ui#289]
### Bug Report

Issue: The chart SVG or canvas suddenly disappears.
### Reproduction of the Problem

Use the Blazor UI from Telerik trial version.
Perform actions such as hiding the chart line or adding values.

### Current Behavior

At seemingly random intervals, the chart SVG or canvas disappears. This occurs when performing actions like hiding the chart line or adding values. The issue does not occur consistently or under obvious conditions.
### Expected/Desired Behavior

The chart should behave as expected and not disappear unexpectedly.
### Environment

* **Telerik UI for Blazor version:** 5.1.1 (Trial)
* **Browser:** All
* **App Type:** Server

**Comment by dimodi** [comment]
@FenixCrafter I see that you have already submitted a forum thread at telerik.com. This GitHub repo is not actively monitored and does not serve as a support channel.
