### ISSUE TITLE
The Callback Event Message Box sample opens the dialog on all browser instances

### ISSUE THREAD

**Issue by marin-bratanov** [telerik/blazor-ui#52]
### Bug report

This sample https://github.com/telerik/blazor-ui/tree/master/common/message-box/callback-event shows the dialog on all browsers that are currently open.

I am opening this on behalf of a customer who submitted a support ticket for this (1485201). @sylvainonweb could you take a look - this is a project that you contributed and perhaps that behavior would manifest in the app that you made it for too.

### Reproduction of the problem

1. Launch the project on two different browser instances.

1. On one of the browser, click the "Show confirmation message box".

### Current behavior

Window Popup appeared on both browser instances.

[2020-09-18-11-10-20-mkv.zip](https://github.com/telerik/blazor-ui/files/5244134/2020-09-18-11-10-20-mkv.zip)

### Expected/desired behavior

the message box shows only on the browser that triggered the click.

**Comment by sylvainonweb** [comment]
I created a pull request which correct this bug which was due to the use of the static keyword in MessageBoxService

`public static event Action<string, string, MessageBoxButtonTypeEnum, Action<MessageBoxResultEnum>> OnShowMessageBox;`

**Comment by marin-bratanov** [comment]
Thank you for the fast reaction and the fix, Sylvain!
