### ISSUE TITLE
CSS for k-drawer-container needs to be calc(100vh - 80px) to fit to the page

### ISSUE THREAD

**Issue by JAugustusSmith** [telerik/blazor-ui#90]
Current page in the example always produces a scrollbar, 
calc(100vh - 80px) fixes the issue

**Comment by xristianstefanov** [comment]
This is fixed in https://github.com/telerik/blazor-ui/pull/92 It is fixed without calc, in this app, there is no layout so, setting the height to 100% in the MainLayout.razor page did the job. Your approach is also valid if it fits the layout of your app and your aims.

**Comment by JAugustusSmith** [comment]
This needs to be fixed in the Blazing Coffee example as well
